const API_INITIAL = 0;
const API_FETCHING = 100;
const API_PAGINATION_FINISHED = 300;
const API_CLIENT_ERROR = 400;
const API_SERVER_ERROR = 500;

export default {
  API_INITIAL,
  API_FETCHING,
  API_PAGINATION_FINISHED,
  API_CLIENT_ERROR,
  API_SERVER_ERROR
};
